

services:
  app:
    build: .
    container_name: warehouse
    volumes:
      - .:/var/www/html
    ports:
      - "9001:80"  # Ensure port 9000 is mapped to container port 80
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: warehouse_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: db_warehouse
      MYSQL_USER: warehoue_admin
      MYSQL_PASSWORD: 1t@dm1N
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
